name: Python Linting and Formatting

on:
  pull_request:
    branches:
      - main
      - linter
  push:
    branches:
      - main
      - linter

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install black
          pip install "black[jupyter]"

      - name: Run black
        run: |
          black --check .  # This will only check formatting, no changes are made

      - name: Run pylint
        run: |
          pylint --max-line-length=100 --disable=C0114,C0115,C0116  # Customize as needed
