name: Python Linting and Formatting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # Optionally, you can trigger on other branches or tags.

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you want

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black  # Install pylint and black

      # Run black (autoformat the code)
      - name: Run black
        run: |
          black --check .  # This will only check formatting, no changes are made

      # Run pylint (linting the code)
      - name: Run pylint
        run: |
          pylint --max-line-length=100 --disable=C0114,C0115,C0116  # Customize as needed
